$(document).ready(function(){
    $(".owl-carousel").owlCarousel(
    {
        center: true,
        items:3,
        loop:true,
        center:true,
        nav:false,
        rewind:false,
        lazyLoad:true,
        autoplay:true,
        autoplayHoverPause:true,
        responsive:{
            576:{
                items:1
            },
            768:{
                items:2
            },
            992:{
                items:3
            }
        }
    })
});